export type EventType='MEETUP'|'WORKSHOP'|'CONFERENCE'|'HACKATHON'|'OTHER';
export type AttendanceMode='ONLINE'|'OFFLINE'|'HYBRID';
export interface EventItem{id:string;title:string;organizer?:string;description?:string;tags:string[];categories:string[];eventType:EventType;startAt:string;endAt?:string;locationName?:string;city:string;address?:string;attendanceMode:AttendanceMode;sourceUrl:string;sourceName:string;status:string}
export interface User{id:string;displayName:string;email?:string;phoneNumber?:string;whatsappOptIn:boolean;preferredCity?:string;preferredEventTypes:EventType[];attendanceMode?:AttendanceMode;role?:string;interests:string[];profileLink1?:string;profileLink2?:string;profileLink3?:string}
export interface NotificationItem{id:string;eventId?:string;type:string;title:string;body:string;createdAt:string}
export interface Recommendation{event:EventItem;score:number;group:'BEST'|'MEDIUM'|'RELATED';reasons:string[]}
export interface ChatReply{sessionId:string;state:string;message:string;completed:boolean}
export interface GroupMessage{id:string;userId?:string;author:string;role:'USER'|'ASSISTANT'|'SYSTEM';content:string;createdAt:string}
export interface GroupMember{id:string;displayName:string;preferredCity?:string;interests:string[];joinedAt:string}
export interface Group{id:string;eventId:string;name:string;memberIds:string[];members:GroupMember[];messages:GroupMessage[]}
export interface PublicProfile{id:string;displayName:string;preferredCity?:string;interests:string[];profileLink1?:string;profileLink2?:string;profileLink3?:string;matchScore:number}
export interface DirectMessage{id:string;senderId:string;recipientId:string;senderName:string;content:string;createdAt:string}
export type MessageRequestStatus='PENDING'|'ACCEPTED'|'REJECTED';
export type MessageDirection='NONE'|'INCOMING'|'OUTGOING';
export interface MessageThread{status:'NONE'|MessageRequestStatus;direction:MessageDirection;requestId?:string;messages:DirectMessage[]}
export interface MessageRequest{id:string;requester:PublicProfile;recipient:PublicProfile;status:MessageRequestStatus;createdAt:string}
export interface MessageInbox{incoming:MessageRequest[];outgoing:MessageRequest[]}
export interface Conversation{user:PublicProfile;lastMessage?:DirectMessage;lastMessageAt?:string;unreadCount:number}
export interface TaxonomyCategory{name:string;tags:string[]}
